name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm release:version
          # publish: pnpm release:publish
          createGithubReleases: true
          commit: 'update-version'
          title: Update Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo github.ref
        env:
          REF: ${{ github.ref }}
          REF_NAME: ${{ github.ref_name }}
          PUSH_HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: 'echo ref: $REF ref_name: $REF_NAME push_head_commit_message: $PUSH_HEAD_COMMIT_MESSAGE'

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        if: ${{ contains(github.event.head_commit.message, 'changeset-release/main') }}
        with:
          draft: true
          target_commitish: ${{ github.sha }}
