name: Test Chaining

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
  release: ## For manual releasing
    types:
      - published

jobs:
  echo-message: ## Check head_commit for changeset-release/main
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_commit.message, 'changeset-release/main') }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: |
          echo "Running head_commit message: ${{ github.event.workflow_run.head_commit.message }} head_branch: ${{ github.event.workflow_run.head_branch }} commit contains phrase update-version: ${{ contains(github.event.workflow_run.head_commit.message, 'changeset-release/main') }} event_name: ${{ github.event_name}}"

## Check services release for workflow_run head_commit for changeset-release/main
## Add manual release trigger
## Pin changesets release versions for all packages
