name: Test Chaining

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  echo-message:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_commit.message == 'update-version'}}
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Running"
